### ISSUE TITLE
Working together

### ISSUE THREAD

**Issue by kiquenet** [iancooper/Paramore#53]
I'm newbie about distributed systems.

IMHO, The ideal world is working together Paramore (https://github.com/iancooper/Paramore/) and Wolfpack (https://wolfpack.codeplex.com/) and another like:

Asimov Deploy https://github.com/asimov-deploy by Torkel Ödegaard (@torkelo). 

https://periscope.codeplex.com/Wikipage?ProjectName=periscope

https://github.com/chucknorris/dropkick
https://github.com/mmooney/Sriracha.Deploy
https://github.com/asimov-deploy/asimov-deploy-winagent
http://presto.codeplex.com/

https://wolfpack.codeplex.com/

From all the good answers provided by everyone here I am now getting a better understanding of appropriate use of this topic and IMHO other programmers will definitely benifit from the 

knowledge sharing here. Some of the implementations that I had worked in the past could have been better implemented using this knowledge. 
_IMHO, better samples  for minimize learning curve are real applications **with full source code** and good patterns_

Now this is the kind of invetigative reporting, that I am interested in. Real world problems, with real world solutions. Most real world solutions start with kick ass debugging.

**Comment by iancooper** [comment]
Hi @kiquenet,

Thanks for the steer on wolfpack. We are looking at our management and monitoring proposition right now, so I'll add your suggestion into that issue and we can review. The summary would be that we think logging our monitoring information to a control bus then providing adapters to varied monitoring toolkits is the most friendly way of delivering this, as many people already have their own infrastructure they want to exploit and we need to provide the hooks for them.

We hear you on examples and sample code as well. We are actively working on our documentation, our basic examples, and the fuller example Rewind (which fell a bit behind). We are very open to linking to sample projects, with documentation, built by others, or to blog posts from others too. It's always great if folks can help out there, as the closer you are to a project the harder it is to see how to document for a newbie.

I would tend to leave deployment to individual projects. One of our goals was to try and make this a useable as possible with your existing infrastructure rather than providing a suggested infrastructure in the way that, for example, DropWizard does. We leave it to others right now, to package up Brighter in those contexts.

Thanks for the interest in the project though
